# See our guides for writing custom images:
# https://coder.com/docs/guides/customization

FROM codercom/enterprise-base:ubuntu

COPY ./coder /coder

# Install programs
# RUN apt-get update && apt-get install -y ...
